### PR TITLE
Fix up awp scope

### PR DESCRIPTION
**Pull request by meepen**
Sorry about the newline shit, it's Atom's fault.

I also added a few hacks that are going to be needed in the future and with the awp.

### CODE REVIEW

**Comment by Cynosphere** [comment]
why the hell are there a bunch of \t's in the awp code, it's gonna error to hell (and it looks ugly)

**Comment by Cynosphere** [comment]
screw it i'll fix it

**Comment by meepen** [comment]
wwoooops, late night codes with meep will fix

**Comment by meepen** [comment]
Fixed it, sorry.

**Comment by meepen** [comment]
This isn't finished yet, let me do some other things.

**Comment by meepen** [comment]
@Python1320 it should work completely now.

**Comment by meepen** [comment]
wait let me fix tabs

**Pull request closed without merging**
